### ISSUE TITLE
360技术总监，就直接偷别人代码的吗？

### ISSUE THREAD

**Issue by dozer47528** [tonydeng/api-blueprint-docker#7]
我的项目：https://github.com/dozer47528/api-blueprint-docker
虽然没什么技术含量，也没多少代码，但是是我自己研究的成果。

你也真是厉害啊，直接复制过来，翻译成中文，就变成你的了？
项目结构，readme 结构都不带改一下的。

佩服佩服！

**Comment by dozer47528** [comment]
https://github.com/tonydeng/architect-manual/issues/14

**Comment by tonydeng** [comment]
@dozer47528 ,首先谢谢你对开源世界的贡献。的确，我在学习和尝试API-Blueprint的使用中借鉴和学习了你的项目中的思路。

这个项目只是用于学习的一个过程产物。如果需要我在这个项目中添加上你的项目的链接以及贡献，这个可以直接和我联系或者进行维权提出其他的要求（如删除等）。

但是这样来直接进行扣帽子，是否也太过偏激了。
